version: '3'
services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_DATABASE: gov_employees_credit
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"