spring:
  application:
    name: employees-credit

  # Database
  datasource:
    url: jdbc:mysql://localhost:3306/gov_employees_credit
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect


management:
  endpoints:
    web:
      exposure:
        include: *
  endpoint:
    health:
      show-details: always

info:
  app:
    name: Gov Employees Credit
    description: Platform designed specifically for processing and approving credit applications from government employees in Cuba
    version: 1.0.0
    maintainer: alejsant75@gmail.com

# Server
server:
  port: 8080

