# Spring application configuration
spring:
  application:
    name: employees-credit

  # Datasource configuration for MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/employees_credit
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA configuration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


# Management endpoint configuration
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

# Application metadata
info:
  app:
    name: Gov Employees Credit
    description: Platform designed specifically for processing and approving credit applications from government employees in Cuba
    version: 1.0.0
    maintainer: alejsant75@gmail.com

# Security configuration for JWT
security:
  jwt:
    secret-key: ${JWT_SECRET_KEY:8071b7d6c05b9afdb77a7ff144762e93c29f87db2c3162f0c17635a7d89035d3}
    expiration: 3600000